name: test action
on:
  push:
    branches:
      - v2
      - v2-action-testing
  workflow_dispatch:

jobs:
  install:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kayac/ecspresso@v0
        with:
          version: v1.5.0
      - run: |
          ecspresso version 2>&1 | fgrep v1.5.0
      - uses: kayac/ecspresso@v1
        with:
          version: v1.6.0
      - run: |
          ecspresso version 2>&1 | fgrep v1.6.0
      - uses: kayac/ecspresso@v1
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v1.7.
      - uses: kayac/ecspresso@v2
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v2.
      - uses: kayac/ecspresso@v2
        with:
          version: v1.7.14
      - run: |
          ecspresso version 2>&1 | fgrep v1.7.14
      - uses: kayac/ecspresso@v2
        with:
          version-file: tests/.ecspresso-version
      - run: |
          ecspresso version 2>&1 | fgrep v2.0.0

      - run: |
          rm -f /usr/local/bin/ecspresso

      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v2.
      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: v2.0.4
      - run: |
          ecspresso version 2>&1 | fgrep v2.0.4
